name: Automate login

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  automate-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb unzip curl

      - name: Install Latest ChromeDriver
        run: |
          LATEST_CHROMEDRIVER_URL=$(curl -sS https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | \
          jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')

          echo "Downloading ChromeDriver from: $LATEST_CHROMEDRIVER_URL"
          curl -o /tmp/chromedriver.zip "$LATEST_CHROMEDRIVER_URL"
          unzip /tmp/chromedriver.zip -d /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Start Xvfb (Virtual Display for Headless Mode)
        run: Xvfb :99 -screen 0 1920x1080x16 &
        env:
          DISPLAY: :99

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager pytz

      - name: Run login.py script
        run: |
          python login.py
        env:
          GREYT_PASSWORD: ${{ secrets.GREYT_PASSWORD }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          DISPLAY: :99
