name: Automate login

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  automate-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager pytz

      - name: Run login.py script
        run: python login.py
        env:
          GREYT_PASSWORD: ${{ secrets.GREYT_PASSWORD }}
