name: Automate Login

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  automate-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip curl google-chrome-stable xvfb

      - name: Start Xvfb (Virtual Display for Head Mode)
        run: Xvfb :99 -screen 0 1920x1080x16 &
        env:
          DISPLAY: :99

      - name: Install ChromeDriver (Latest Compatible)
        run: |
          # Fetch latest stable Chrome version
          LATEST_CHROME_VERSION=$(curl -sS https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r '.channels.Stable.version')
          echo "Latest Chrome version: $LATEST_CHROME_VERSION"

          # Fetch latest ChromeDriver matching the stable version
          CHROMEDRIVER_URL=$(curl -sS https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | jq -r ".channels.Stable.downloads.chromedriver[] | select(.platform == \"linux64\") | .url")
          echo "Downloading ChromeDriver from: $CHROMEDRIVER_URL"

          wget -q -O /tmp/chromedriver.zip "$CHROMEDRIVER_URL"
          unzip /tmp/chromedriver.zip -d /tmp/chromedriver
          sudo mv /tmp/chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

          # Verify installation
          google-chrome --version
          chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager pytz jq

      - name: Run login.py script
        run: python login.py
        env:
          GREYT_PASSWORD_USER1: ${{ secrets.GREYT_PASSWORD_USER1 }}
          GREYT_PASSWORD_USER2: ${{ secrets.GREYT_PASSWORD_USER2 }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          DISPLAY: :99
