name: Automate Login

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  automate-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb

      - name: Start Xvfb (Virtual Display for Head Mode)
        run: Xvfb :99 -screen 0 1920x1080x16 &
        env:
          DISPLAY: :99

      - name: Install Chrome and ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d "." -f1)
          echo "Detected Chrome version: $CHROME_VERSION"

          # Fetch ChromeDriver matching the major version
          wget -q -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}.0.0/linux64/chromedriver-linux64.zip"

          # Unzip and move ChromeDriver
          unzip /tmp/chromedriver.zip -d /tmp/chromedriver
          sudo mv /tmp/chromedriver/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

          # Verify installation
          chromedriver --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver_manager pytz

      - name: Run login.py script
        run: python login.py
        env:
          GREYT_PASSWORD: ${{ secrets.GREYT_PASSWORD }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          DISPLAY: :99
